Repository cyfronet-fid/marketplace, pull requests merged in 2021-05, with the labels that each got.

#1996 [#1885] Ordering API happy paths and cypress customization
  .github/workflows/e2e.yml
  .gitignore
  app/controllers/users/auth_mock_controller.rb
  app/views/home/_info.html.haml
  app/views/layouts/_sections.html.haml
  app/views/projects/edit.html.haml
  app/views/projects/nav/_projects.html.haml
  app/views/projects/new.html.haml
  config/application.rb
  config/routes.rb
  e2e/.tool-versions
  e2e/cypress/integration/sanity.spec.ts
  spec/controllers/auth_mock_controller_spec.rb
  test/system/README.md
  test/system/cypress.json
  test/system/cypress/factories/project.factory.ts
  test/system/cypress/factories/user.factory.ts
  test/system/cypress/integration/offers.spec.ts
  test/system/cypress/integration/sanity.spec.ts
  test/system/cypress/plugins/index.js
  test/system/cypress/support/auth.ts
  test/system/cypress/support/coverage.js
  test/system/cypress/support/index.ts
  test/system/cypress/support/jira.ts
  test/system/cypress/support/offers.ts
  test/system/cypress/support/utilities.ts
  test/system/package-lock.json
  test/system/package.json
  test/system/tsconfig.json
Labels: enhancement

#2046 [#1960] fix change offer with step bar, increase Capybara failed tests re-run, setup max acceptable bots Crawl Delay
  app/helpers/order_nav_helper.rb
  config/robots.production.txt
  db/data.yml
  lib/tasks/dev.rake
  spec/rails_helper.rb
Labels: bug

#2058 Dependabot updates
  Gemfile.lock
  yarn.lock
Labels: dependencies, javascript, ruby

#2053 [#1836] Fix img background on resize
  CHANGELOG.md
  app/controllers/users/auth_mock_controller.rb
  app/helpers/provider_helper.rb
  app/services/importers/logo.rb
  app/views/backoffice/providers/show.html.haml
  docs/upgrade/3.12.0.md
  lib/tasks/add_extensions_to_images.rake
Labels: bug

#2023 Don't recommend unpublished services
  app/controllers/concerns/service/recommendable.rb
  app/serializers/recommender/service_serializer.rb
Labels: bug

#2057 Auth mock extension
  app/controllers/users/auth_mock_controller.rb
Labels: enhancement
